services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root_password || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
        - my-db:/var/lib/mysql
    networks:
        - bank-network


  accounts:
    image: "saurabh36/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql/easy_microservice_accounts?createDatabaseIfNotExist=true"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network

  loan:
    image: "saurabh36/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql/easy_microservice_loans?createDatabaseIfNotExist=true"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network

  cards:
    image: "saurabh36/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql/easy_microservice_cards?createDatabaseIfNotExist=true"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network
networks:
  bank-network:
    driver: "bridge"
volumes:
  my-db:


