spring:
  application:
    name: accounts

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy_microservice_accounts
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: default
server:
  port: 8080

#// custom properties
build:
  version: "3.0"
accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
