server:
  port: 8080

spring:
  application:
    name: "accounts"

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy_microservice_accounts
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    loadbalancer:
      retry:
        enabled: true

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true # to check health of the service if its down then its won't receive traffic
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : "http://localhost:8070/eureka/"

