spring:
  application:
    name: accounts

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy_microservice_accounts
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
